name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version of Node.js your project uses

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm test  # Use the npm test script to run Cypress
