name: Run Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Explicitly install Cypress binary
      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run --spec 'cypress/e2e/**/*'

      - name: Upload Cypress videos and screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos-and-screenshots
          path: |
            cypress/videos
            cypress/screenshots
